### ISSUE TITLE
.NET Core 3.0 support

### ISSUE THREAD

**Issue by dude0001** [ocha/ansible-role-dotnet-core#8]
Is this being worked on and is there any ETA?

**Comment by ocha** [comment]
Have you tried using config variables to point to 3.0 release?

**Comment by dude0001** [comment]
Sorry, I am a bit green with Ansible. I see this is mentioned in the readme and my team confirmed this was an option as well. We'll give it a try. I'll try to leave feedback here with how it goes.

**Comment by dude0001** [comment]
Sorry, I am a bit green with Ansible. I see this is mentioned in the readme and my team confirmed this was an option as well. We'll give it a try. I'll try to leave feedback here with how it goes.

**Comment by till** [comment]
Works flawlessly:

```
dotnet_package: "dotnet-sdk-3.0"
```

Thank you for this role!

**Comment by ocha** [comment]
Thank you @till for your comment. @dude0001 I hope that helps.
